### ISSUE TITLE
json parameters support

### ISSUE THREAD

**Issue by holmla** [leonardoxh/AsyncOkHttpClient#21]
Simple parameters seem to map to json allright, but more complex ones don't flow so fluently. Would like to have option of passing parameters as a json object.

ie simple key / value pairs seem to end up as properly formed json, but when value is a collection of key/value pairs itself, allsorts of escaping happens and it ends up broken. 

I came to this library from the loopj async library, but it had issues with sni, now this library handles sni but has issues with json. I can help with fixing if time is a constraint.

**Comment by leonardoxh** [comment]
Hi, agreed.

Tanks for open this issue time isn't a constraint (because this library doesn't have all the features that I have planned yet).

I can do this over this week with the other features that I already wrote but not pushed yet :$

And yes, your help is very welcome

**Comment by holmla** [comment]
Ok, ill try to write json parameters support and will submit a pull request once its ready. What is your release plan? When is next release coming up ?

**Comment by leonardoxh** [comment]
Next week probably

**Comment by holmla** [comment]
Hello again, had a chat with the team and decided to switch to okhttp library since it supports json as is. Sorry, I won't be contributing json support for you, but then again, I won't be demanding it either=). 

Thanks for the quick responses, and have a good release!
